export type SeedProvider = {
  name: string;
  organizationType: "national" | "local" | "private" | "community";
  officialUrl?: string;
  country?: string;
};

export type SeedSource = {
  providerName: string;
  name: string;
  nameEn?: string;
  description: string;
  officialUrl: string;
  endpointUrl?: string;
  documentationUrl?: string;
  category: string;
  dataFormat: string;
  accessType: string;
  requiresApiKey: boolean;
  apiKeyEnvName?: string;
  licenseName?: string;
  commercialUse: "allowed" | "restricted" | "unknown";
  attributionRequired: boolean;
  updateFrequency?: string;
  trustLevel: number;
  qualityScore: number;
  note?: string;
  tags: string[];
  useCases: { useCaseName: string; targetSystem?: string; description?: string }[];
};

export const INITIAL_TAGS: { name: string; color: string }[] = [
  { name: "災害", color: "#dc2626" },
  { name: "河川", color: "#0ea5e9" },
  { name: "道路", color: "#6b7280" },
  { name: "地形", color: "#92400e" },
  { name: "標高", color: "#b45309" },
  { name: "気象", color: "#2563eb" },
  { name: "交通", color: "#7c3aed" },
  { name: "都市計画", color: "#059669" },
  { name: "3D都市", color: "#0891b2" },
  { name: "維持管理", color: "#4b5563" },
  { name: "施工判断", color: "#ea580c" },
  { name: "工事候補地", color: "#ca8a04" },
  { name: "統計", color: "#9333ea" },
  { name: "自治体", color: "#16a34a" },
  { name: "APIキー必要", color: "#e11d48" },
  { name: "利用条件要確認", color: "#f59e0b" },
];

/** RBAC既定ロール（docs/design/rbac-design.md §2）。priorityは高いほど強い。 */
export const DEFAULT_ROLES: { name: string; priority: number; note: string }[] = [
  { name: "viewer", priority: 10, note: "閲覧者（既定）。検索・地図・地形・気象・判定結果の閲覧" },
  { name: "engineer", priority: 20, note: "技術者。現場登録・判定実行・レポート出力・ウォッチリスト" },
  { name: "data-steward", priority: 30, note: "データ管理者。データソース登録・収集ジョブ・品質再計算" },
  { name: "admin", priority: 40, note: "管理者。管理API・設定・タグ・ロール管理" },
  { name: "auditor", priority: 35, note: "監査。監査ログ・判定スナップショット・証跡の参照のみ" },
  { name: "api-consumer", priority: 15, note: "API利用者。契約済みAPIキー経由の read / 限定 write" },
];

export const PROVIDERS: SeedProvider[] = [
  { name: "国土交通省", organizationType: "national", officialUrl: "https://www.mlit.go.jp/", country: "日本" },
  { name: "国土地理院", organizationType: "national", officialUrl: "https://www.gsi.go.jp/", country: "日本" },
  { name: "気象庁", organizationType: "national", officialUrl: "https://www.jma.go.jp/", country: "日本" },
  { name: "総務省統計局", organizationType: "national", officialUrl: "https://www.stat.go.jp/", country: "日本" },
  { name: "OpenStreetMap Foundation", organizationType: "community", officialUrl: "https://www.openstreetmap.org/", country: "国際" },
  { name: "日本道路交通情報センター(JARTIC)", organizationType: "private", officialUrl: "https://www.jartic.or.jp/", country: "日本" },
  { name: "防災科学技術研究所", organizationType: "national", officialUrl: "https://www.bosai.go.jp/", country: "日本" },
  { name: "内閣府", organizationType: "national", officialUrl: "https://www.cao.go.jp/", country: "日本" },
  { name: "環境省", organizationType: "national", officialUrl: "https://www.env.go.jp/", country: "日本" },
  { name: "デジタル庁", organizationType: "national", officialUrl: "https://www.digital.go.jp/", country: "日本" },
  { name: "科学技術振興機構(JST)", organizationType: "national", officialUrl: "https://www.jst.go.jp/", country: "日本" },
  { name: "国立情報学研究所(NII)", organizationType: "national", officialUrl: "https://www.nii.ac.jp/", country: "日本" },
  { name: "工業所有権情報・研修館(INPIT)", organizationType: "national", officialUrl: "https://www.inpit.go.jp/", country: "日本" },
  { name: "産業技術総合研究所", organizationType: "national", officialUrl: "https://www.aist.go.jp/", country: "日本" },
  { name: "JAXA", organizationType: "national", officialUrl: "https://www.jaxa.jp/", country: "日本" },
  { name: "USGS", organizationType: "national", officialUrl: "https://www.usgs.gov/", country: "米国" },
  { name: "東京都", organizationType: "local", officialUrl: "https://www.metro.tokyo.lg.jp/", country: "日本" },
  { name: "静岡県", organizationType: "local", officialUrl: "https://www.pref.shizuoka.jp/", country: "日本" },
  { name: "北海道", organizationType: "local", officialUrl: "https://www.pref.hokkaido.lg.jp/", country: "日本" },
  { name: "BODIK(オープンデータ推進)", organizationType: "community", officialUrl: "https://www.bodik.jp/", country: "日本" },
  { name: "Open-Meteo", organizationType: "private", officialUrl: "https://open-meteo.com/", country: "スイス" },
];

/** 初期10件 + 拡充40件 = 50件 */
export const SOURCES: SeedSource[] = [
  // ===== 初期10件 =====
  {
    providerName: "国土交通省",
    name: "国土数値情報",
    nameEn: "National Land Numerical Information",
    description:
      "地形、土地利用、公共施設、交通、災害リスク、都市計画、地価など国土に関する基礎的なGISデータを無償提供。",
    officialUrl: "https://nlftp.mlit.go.jp/ksj/",
    documentationUrl: "https://nlftp.mlit.go.jp/ksj/other/agreement.html",
    category: "gis",
    dataFormat: "GeoJSON",
    accessType: "download",
    requiresApiKey: false,
    licenseName: "国土数値情報ダウンロードサービス利用約款",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "yearly",
    trustLevel: 5,
    qualityScore: 90,
    tags: ["災害", "都市計画", "地形", "交通"],
    useCases: [
      {
        useCaseName: "工事候補地の災害リスク確認",
        targetSystem: "Site Risk Checker",
        description: "土砂災害警戒区域・浸水想定区域データの活用",
      },
    ],
  },
  {
    providerName: "国土交通省",
    name: "PLATEAU",
    nameEn: "Project PLATEAU",
    description:
      "国土交通省主導の3D都市モデル整備・活用・オープンデータ化プロジェクト。CityGML形式の都市モデルを提供。",
    officialUrl: "https://www.mlit.go.jp/plateau/",
    endpointUrl: "https://www.geospatial.jp/ckan/dataset/plateau",
    category: "3d-city",
    dataFormat: "CityGML",
    accessType: "download",
    requiresApiKey: false,
    licenseName: "PLATEAU Sites 利用規約 (CC BY 4.0 相当)",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "yearly",
    trustLevel: 5,
    qualityScore: 85,
    tags: ["3D都市", "都市計画"],
    useCases: [{ useCaseName: "都市デジタルツイン構築", description: "建物・都市構造の3D可視化" }],
  },
  {
    providerName: "国土交通省",
    name: "xROAD 道路データプラットフォーム",
    nameEn: "xROAD",
    description: "国土交通省道路局の道路データ利活用DX施策。道路基盤地図情報、交通量データ等の公開を推進。",
    officialUrl: "https://www.xroad.mlit.go.jp/",
    category: "road",
    dataFormat: "other",
    accessType: "web",
    requiresApiKey: false,
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 4,
    qualityScore: 70,
    note: "データセットごとに利用条件が異なるため個別確認が必要",
    tags: ["道路", "交通", "維持管理", "利用条件要確認"],
    useCases: [{ useCaseName: "建設物流ルート検討", targetSystem: "Logistics Route Planner" }],
  },
  {
    providerName: "国土交通省",
    name: "道路構造物管理情報",
    nameEn: "Road Structures DB",
    description: "全国の橋梁・トンネル等の道路構造物の諸元・点検情報を公開する国土交通省のデータベース。",
    officialUrl: "https://road-structures-db.mlit.go.jp/",
    category: "road",
    dataFormat: "HTML",
    accessType: "web",
    requiresApiKey: false,
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 4,
    qualityScore: 65,
    tags: ["道路", "維持管理", "利用条件要確認"],
    useCases: [{ useCaseName: "インフラ維持管理マップ", targetSystem: "Infrastructure Maintenance Map" }],
  },
  {
    providerName: "日本道路交通情報センター(JARTIC)",
    name: "JARTIC 交通量API",
    nameEn: "JARTIC Traffic Volume API",
    description: "常時観測交通量データ等を提供するAPI。xROAD施策と連携した道路交通データ源。",
    officialUrl: "https://www.jartic.or.jp/",
    endpointUrl: "https://api.jartic-open-traffic.org/geoserver",
    category: "road",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: false,
    commercialUse: "restricted",
    attributionRequired: true,
    updateFrequency: "hourly",
    trustLevel: 4,
    qualityScore: 70,
    tags: ["交通", "道路", "利用条件要確認"],
    useCases: [{ useCaseName: "工事車両の交通量影響確認", description: "施工計画時の周辺交通量把握" }],
  },
  {
    name: "地理院タイル",
    providerName: "国土地理院",
    nameEn: "GSI Tiles",
    description: "標準地図、写真、標高タイルなどをXYZ形式で提供する国土地理院の地図タイルサービス。",
    officialUrl: "https://maps.gsi.go.jp/development/ichiran.html",
    endpointUrl: "https://cyberjapandata.gsi.go.jp/xyz/std/5/28/12.png",
    documentationUrl: "https://maps.gsi.go.jp/development/siyou.html",
    category: "map-elevation",
    dataFormat: "PNG",
    accessType: "tile",
    requiresApiKey: false,
    licenseName: "国土地理院コンテンツ利用規約",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 5,
    qualityScore: 90,
    tags: ["地形", "道路"],
    useCases: [{ useCaseName: "現場周辺の地図表示", description: "背景地図としての利用" }],
  },
  {
    name: "国土地理院 標高API",
    providerName: "国土地理院",
    nameEn: "GSI Elevation API",
    description: "指定した緯度経度の標高値をJSONで返すAPI。地形・災害リスク分析の基礎データとして利用可能。",
    officialUrl: "https://maps.gsi.go.jp/development/elevation_s.html",
    endpointUrl:
      "https://cyberjapandata2.gsi.go.jp/general/dem/scripts/getelevation.php?lon=140.08531&lat=36.103543&outtype=JSON",
    category: "map-elevation",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: false,
    licenseName: "国土地理院コンテンツ利用規約",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 5,
    qualityScore: 90,
    tags: ["標高", "地形", "工事候補地"],
    useCases: [{ useCaseName: "工事候補地の標高・地形確認", targetSystem: "Site Risk Checker" }],
  },
  {
    providerName: "気象庁",
    name: "気象庁 防災情報XML",
    nameEn: "JMA Disaster Prevention Information XML",
    description: "気象警報・地震・津波等の防災情報をXML形式でPULL型提供。Atomフィードから電文を取得できる。",
    officialUrl: "https://xml.kishou.go.jp/",
    endpointUrl: "https://www.data.jma.go.jp/developer/xml/feed/regular.xml",
    documentationUrl: "https://xml.kishou.go.jp/xmlpull.html",
    category: "weather",
    dataFormat: "XML",
    accessType: "API",
    requiresApiKey: false,
    licenseName: "気象庁ホームページ利用規約 (CC BY 4.0 互換)",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "realtime",
    trustLevel: 5,
    qualityScore: 85,
    tags: ["気象", "災害", "施工判断"],
    useCases: [{ useCaseName: "気象・河川による施工判断支援", targetSystem: "Weather & Water Decision" }],
  },
  {
    providerName: "総務省統計局",
    name: "e-Stat API",
    nameEn: "e-Stat API",
    description:
      "政府統計の総合窓口。人口、地域統計、産業統計等をREST APIで機械判読可能な形式で提供。APIキー(appId)が必要。",
    officialUrl: "https://www.e-stat.go.jp/api/",
    endpointUrl: "https://api.e-stat.go.jp/rest/3.0/app/json/getStatsList",
    documentationUrl: "https://www.e-stat.go.jp/api/api-info/e-stat-manual",
    category: "statistics",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: true,
    apiKeyEnvName: "ESTAT_APP_ID",
    licenseName: "e-Stat 利用規約",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "monthly",
    trustLevel: 5,
    qualityScore: 85,
    tags: ["統計", "APIキー必要"],
    useCases: [{ useCaseName: "地域人口・産業統計の把握", description: "工事エリアの地域特性分析" }],
  },
  {
    providerName: "OpenStreetMap Foundation",
    name: "OpenStreetMap (Overpass API)",
    nameEn: "OpenStreetMap",
    description:
      "コミュニティによる自由な地図データ。道路、施設、POI等をOverpass APIで取得可能。ODbLライセンス。",
    officialUrl: "https://www.openstreetmap.org/",
    endpointUrl: "https://overpass-api.de/api/status",
    documentationUrl: "https://wiki.openstreetmap.org/wiki/Overpass_API",
    category: "map",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: false,
    licenseName: "ODbL 1.0",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "realtime",
    trustLevel: 4,
    qualityScore: 75,
    note: "再配布時はODbLの条件(出典表記・同一ライセンス)に従うこと",
    tags: ["道路", "地形"],
    useCases: [{ useCaseName: "現場周辺施設の確認", description: "POI・道路網の参照" }],
  },

  // ===== 拡充40件 =====
  {
    providerName: "国土地理院",
    name: "ハザードマップポータルサイト",
    description: "洪水・土砂災害・津波等のリスク情報を重ねて表示できるポータル。重ねるハザードマップのタイルも公開。",
    officialUrl: "https://disaportal.gsi.go.jp/",
    category: "weather",
    dataFormat: "PNG",
    accessType: "tile",
    requiresApiKey: false,
    licenseName: "国土地理院コンテンツ利用規約",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 5,
    qualityScore: 85,
    tags: ["災害", "工事候補地"],
    useCases: [{ useCaseName: "工事候補地の災害リスク確認", targetSystem: "Site Risk Checker" }],
  },
  {
    providerName: "国土交通省",
    name: "川の防災情報",
    description: "河川水位・雨量・洪水予報等のリアルタイム防災情報を提供する国土交通省のサイト。",
    officialUrl: "https://www.river.go.jp/",
    category: "weather",
    dataFormat: "HTML",
    accessType: "web",
    requiresApiKey: false,
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "realtime",
    trustLevel: 5,
    qualityScore: 75,
    note: "2026-08-12 HTTP 200実測確認。",
    tags: ["河川", "災害", "施工判断", "利用条件要確認"],
    useCases: [{ useCaseName: "河川水位による施工判断", targetSystem: "Weather & Water Decision" }],
  },
  {
    providerName: "国土交通省",
    name: "水文水質データベース",
    description: "全国の雨量・水位・水質等の水文観測データを検索・取得できるデータベース。",
    officialUrl: "https://www1.river.go.jp/",
    category: "weather",
    dataFormat: "HTML",
    accessType: "web",
    requiresApiKey: false,
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "daily",
    trustLevel: 5,
    qualityScore: 70,
    tags: ["河川", "気象", "利用条件要確認"],
    useCases: [{ useCaseName: "過去水文データの分析", description: "施工計画時の出水期リスク評価" }],
  },
  {
    providerName: "国土交通省",
    name: "道路交通センサス",
    description: "全国道路・街路交通情勢調査。区間別交通量・旅行速度等の調査結果を公開。",
    officialUrl: "https://www.mlit.go.jp/road/census/r3/",
    category: "road",
    dataFormat: "other",
    accessType: "download",
    requiresApiKey: false,
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 5,
    qualityScore: 70,
    tags: ["道路", "交通", "統計"],
    useCases: [{ useCaseName: "建設物流ルート検討", targetSystem: "Logistics Route Planner" }],
  },
  {
    providerName: "国土交通省",
    name: "国土交通データプラットフォーム",
    nameEn: "MLIT Data Platform",
    description: "国土・経済活動・自然現象に関するデータを横断検索・取得できる国土交通省のプラットフォーム。APIも提供。",
    officialUrl: "https://www.mlit-data.jp/",
    documentationUrl: "https://www.mlit-data.jp/#/apiinfo",
    category: "gis",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: true,
    apiKeyEnvName: "MLIT_DATA_API_KEY",
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 5,
    qualityScore: 75,
    tags: ["統計", "都市計画", "APIキー必要", "利用条件要確認"],
    useCases: [{ useCaseName: "国土データの横断検索", description: "複数データソースの統合参照" }],
  },
  {
    providerName: "国土交通省",
    name: "不動産情報ライブラリ API",
    nameEn: "Real Estate Information Library",
    description: "不動産取引価格・地価公示・都市計画等の不動産関連情報をAPIで提供。",
    officialUrl: "https://www.reinfolib.mlit.go.jp/",
    documentationUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/",
    category: "statistics",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: true,
    apiKeyEnvName: "REINFOLIB_API_KEY",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "quarterly",
    trustLevel: 5,
    qualityScore: 80,
    tags: ["統計", "都市計画", "APIキー必要"],
    useCases: [{ useCaseName: "用地取得コストの概算", description: "取引価格・地価の参照" }],
  },
  {
    providerName: "国土交通省",
    name: "NETIS 新技術情報提供システム",
    description: "公共工事等における新技術の情報を共有するデータベース。技術検索・活用効果の確認が可能。",
    officialUrl: "https://www.netis.mlit.go.jp/netis/",
    category: "construction",
    dataFormat: "HTML",
    accessType: "web",
    requiresApiKey: false,
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 5,
    qualityScore: 70,
    tags: ["維持管理", "施工判断", "利用条件要確認"],
    useCases: [{ useCaseName: "新技術の採用検討", description: "施工計画時の工法比較" }],
  },
  {
    providerName: "国土交通省",
    name: "i-Construction ポータル",
    description: "ICT施工・BIM/CIM等、建設現場の生産性向上施策 i-Construction の情報ポータル。",
    officialUrl: "https://www.mlit.go.jp/tec/i-construction/index.html",
    category: "construction",
    dataFormat: "HTML",
    accessType: "web",
    requiresApiKey: false,
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 5,
    qualityScore: 65,
    tags: ["施工判断", "維持管理"],
    useCases: [{ useCaseName: "ICT施工要領の確認", description: "基準類・要領の参照" }],
  },
  {
    providerName: "気象庁",
    name: "気象庁 天気予報JSON",
    description: "気象庁ホームページで利用されている天気予報データ(JSON)。地域コード単位で取得可能。",
    officialUrl: "https://www.jma.go.jp/bosai/forecast/",
    endpointUrl: "https://www.jma.go.jp/bosai/forecast/data/forecast/130000.json",
    category: "weather",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: false,
    licenseName: "気象庁ホームページ利用規約",
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "hourly",
    trustLevel: 4,
    qualityScore: 70,
    note: "公式なAPI仕様書は非公開のため、仕様変更リスクに注意",
    tags: ["気象", "施工判断", "利用条件要確認"],
    useCases: [{ useCaseName: "現場の天気予報確認", targetSystem: "Weather & Water Decision" }],
  },
  {
    providerName: "気象庁",
    name: "アメダス観測データ(JSON)",
    description: "アメダスの最新観測値をJSONで取得できる気象庁ホームページのデータ。",
    officialUrl: "https://www.jma.go.jp/bosai/map.html",
    endpointUrl: "https://www.jma.go.jp/bosai/amedas/data/latest_time.txt",
    category: "weather",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: false,
    licenseName: "気象庁ホームページ利用規約",
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "realtime",
    trustLevel: 4,
    qualityScore: 70,
    note: "公式なAPI仕様書は非公開のため、仕様変更リスクに注意",
    tags: ["気象", "施工判断", "利用条件要確認"],
    useCases: [{ useCaseName: "現場周辺の雨量・風速確認", description: "作業中止判断の参考" }],
  },
  {
    providerName: "気象庁",
    name: "過去の気象データ検索",
    description: "観測所ごとの過去の気象観測データ(気温・降水量・風等)を検索・表示できるサービス。",
    officialUrl: "https://www.data.jma.go.jp/obd/stats/etrn/",
    category: "weather",
    dataFormat: "HTML",
    accessType: "web",
    requiresApiKey: false,
    licenseName: "気象庁ホームページ利用規約",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "daily",
    trustLevel: 5,
    qualityScore: 75,
    tags: ["気象", "統計"],
    useCases: [{ useCaseName: "施工計画の気象統計分析", description: "月別降雨日数等の把握" }],
  },
  {
    providerName: "気象庁",
    name: "震度データベース検索",
    description: "過去の地震の震度観測データを検索できるデータベース。",
    officialUrl: "https://www.data.jma.go.jp/svd/eqdb/data/shindo/",
    category: "weather",
    dataFormat: "HTML",
    accessType: "web",
    requiresApiKey: false,
    licenseName: "気象庁ホームページ利用規約",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 5,
    qualityScore: 70,
    tags: ["災害", "統計"],
    useCases: [{ useCaseName: "地域の地震履歴確認", targetSystem: "Site Risk Checker" }],
  },
  {
    providerName: "国土地理院",
    name: "基盤地図情報",
    description: "測量の基準となる基盤地図情報(基準点・海岸線・道路縁・建築物等)のダウンロードサービス。",
    officialUrl: "https://fgd.gsi.go.jp/download/menu.php",
    category: "gis",
    dataFormat: "other",
    accessType: "download",
    requiresApiKey: false,
    licenseName: "国土地理院コンテンツ利用規約",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 5,
    qualityScore: 80,
    note: "ダウンロードにはログイン登録が必要",
    tags: ["地形", "都市計画"],
    useCases: [{ useCaseName: "設計用基図の整備", description: "道路縁・建築物外周線の取得" }],
  },
  {
    providerName: "国土地理院",
    name: "地理院地図Vector (ベクトルタイル)",
    description: "ベクトル形式の地図タイル(試験公開)。スタイルを自由に変更できる地図表現が可能。",
    officialUrl: "https://maps.gsi.go.jp/vector/",
    endpointUrl: "https://cyberjapandata.gsi.go.jp/xyz/experimental_bvmap/5/28/12.pbf",
    category: "map-elevation",
    dataFormat: "other",
    accessType: "tile",
    requiresApiKey: false,
    licenseName: "国土地理院コンテンツ利用規約",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 5,
    qualityScore: 75,
    tags: ["地形"],
    useCases: [{ useCaseName: "カスタム地図表現", description: "用途別の地図スタイル作成" }],
  },
  {
    providerName: "国土地理院",
    name: "地理院タイル 空中写真",
    description: "全国最新写真(シームレス)の空中写真タイル。現地状況の俯瞰確認に利用できる。",
    officialUrl: "https://maps.gsi.go.jp/development/ichiran.html#seamlessphoto",
    endpointUrl: "https://cyberjapandata.gsi.go.jp/xyz/seamlessphoto/5/28/12.jpg",
    category: "map-elevation",
    dataFormat: "PNG",
    accessType: "tile",
    requiresApiKey: false,
    licenseName: "国土地理院コンテンツ利用規約",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 5,
    qualityScore: 80,
    tags: ["地形", "工事候補地"],
    useCases: [{ useCaseName: "現場周辺の俯瞰確認", description: "空中写真による現況把握" }],
  },
  {
    providerName: "国土地理院",
    name: "標高タイル",
    description: "標高値をタイル形式(テキスト)で提供。広域の地形解析・断面図生成に利用できる。",
    officialUrl: "https://maps.gsi.go.jp/development/demtile.html",
    endpointUrl: "https://cyberjapandata.gsi.go.jp/xyz/dem/10/906/404.txt",
    category: "map-elevation",
    dataFormat: "CSV",
    accessType: "tile",
    requiresApiKey: false,
    licenseName: "国土地理院コンテンツ利用規約",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 5,
    qualityScore: 80,
    tags: ["標高", "地形"],
    useCases: [{ useCaseName: "広域地形解析", description: "縦横断図の自動生成" }],
  },
  {
    providerName: "国土地理院",
    name: "GEONET 電子基準点データ提供サービス",
    description: "全国の電子基準点(GNSS連続観測点)の観測データを提供。測量・地殻変動監視に利用。",
    officialUrl: "https://terras.gsi.go.jp/",
    category: "map-elevation",
    dataFormat: "other",
    accessType: "web",
    requiresApiKey: false,
    licenseName: "国土地理院コンテンツ利用規約",
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "daily",
    trustLevel: 5,
    qualityScore: 70,
    note: "データ取得には利用者登録が必要",
    tags: ["地形", "利用条件要確認"],
    useCases: [{ useCaseName: "GNSS測量の基準データ取得", description: "工事測量の基準点利用" }],
  },
  {
    providerName: "防災科学技術研究所",
    name: "J-SHIS 地震ハザードステーション",
    nameEn: "J-SHIS",
    description: "確率論的地震動予測地図等の地震ハザード情報を提供。Web APIで地点ごとのハザード情報を取得可能。",
    officialUrl: "https://www.j-shis.bosai.go.jp/",
    endpointUrl: "https://www.j-shis.bosai.go.jp/map/api/pshm/Y2020/AVR/TTL_MTTL/meshinfo.geojson?position=139.767,35.681&epsg=4301",
    documentationUrl: "https://www.j-shis.bosai.go.jp/api-docs",
    category: "weather",
    dataFormat: "GeoJSON",
    accessType: "API",
    requiresApiKey: false,
    licenseName: "J-SHIS 利用規約 (CC BY 4.0)",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "yearly",
    trustLevel: 5,
    qualityScore: 85,
    tags: ["災害", "工事候補地"],
    useCases: [{ useCaseName: "工事候補地の地震ハザード評価", targetSystem: "Site Risk Checker" }],
  },
  {
    providerName: "防災科学技術研究所",
    name: "K-NET / KiK-net 強震観測網",
    description: "全国の強震観測網。強震記録のダウンロードが可能(要利用者登録)。",
    officialUrl: "https://www.kyoshin.bosai.go.jp/",
    category: "weather",
    dataFormat: "other",
    accessType: "web",
    requiresApiKey: false,
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "realtime",
    trustLevel: 5,
    qualityScore: 70,
    note: "データ取得には利用者登録が必要。2026-08-12 HTTP 200実測確認。",
    tags: ["災害", "利用条件要確認"],
    useCases: [{ useCaseName: "構造物の耐震検討用データ取得", description: "強震波形の参照" }],
  },
  {
    providerName: "防災科学技術研究所",
    name: "J-RISQ 地震リスク情報",
    description: "地震発生直後の推定震度分布・被災人口等のリスク情報を提供するサービス。",
    officialUrl: "https://www.j-risq.bosai.go.jp/",
    category: "weather",
    dataFormat: "HTML",
    accessType: "web",
    requiresApiKey: false,
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "realtime",
    trustLevel: 5,
    qualityScore: 65,
    tags: ["災害", "利用条件要確認"],
    useCases: [{ useCaseName: "発災後の被災状況把握", targetSystem: "Disaster Insight Map" }],
  },
  {
    providerName: "内閣府",
    name: "RESAS API",
    nameEn: "RESAS API",
    description: "地域経済分析システム(RESAS)のデータをAPIで提供。人口・産業・観光等の地域データを取得可能。",
    officialUrl: "https://opendata.resas-portal.go.jp/",
    endpointUrl: "https://opendata.resas-portal.go.jp/api/v1/prefectures",
    documentationUrl: "https://opendata.resas-portal.go.jp/docs/api/v1/index.html",
    category: "statistics",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: true,
    apiKeyEnvName: "RESAS_API_KEY",
    licenseName: "RESAS API利用規約",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "yearly",
    trustLevel: 5,
    qualityScore: 80,
    tags: ["統計", "APIキー必要"],
    useCases: [{ useCaseName: "地域経済・人口動態の把握", description: "進出エリアの市場分析" }],
  },
  {
    providerName: "内閣府",
    name: "防災情報のページ",
    description: "内閣府の防災施策・被害状況報告・防災白書等の情報ポータル。",
    officialUrl: "https://www.bousai.go.jp/",
    category: "weather",
    dataFormat: "HTML",
    accessType: "web",
    requiresApiKey: false,
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 5,
    qualityScore: 60,
    tags: ["災害"],
    useCases: [{ useCaseName: "防災施策・被害報の確認", description: "災害対応の一次情報源" }],
  },
  {
    providerName: "環境省",
    name: "そらまめくん (大気汚染物質広域監視)",
    description: "全国の大気汚染常時監視測定局の速報値を提供するシステム。",
    officialUrl: "https://soramame.env.go.jp/",
    category: "weather",
    dataFormat: "HTML",
    accessType: "web",
    requiresApiKey: false,
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "hourly",
    trustLevel: 5,
    qualityScore: 65,
    tags: ["気象", "統計", "利用条件要確認"],
    useCases: [{ useCaseName: "粉じん影響の周辺環境確認", description: "解体・土工事の環境配慮" }],
  },
  {
    providerName: "環境省",
    name: "水環境総合情報サイト",
    description: "公共用水域の水質測定結果等、水環境に関する情報を提供するサイト。",
    officialUrl: "https://water-pub.env.go.jp/water-pub/mizu-site/",
    category: "weather",
    dataFormat: "HTML",
    accessType: "web",
    requiresApiKey: false,
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "yearly",
    trustLevel: 5,
    qualityScore: 60,
    tags: ["河川", "統計", "利用条件要確認"],
    useCases: [{ useCaseName: "河川工事の水質基準確認", description: "環境影響の事前把握" }],
  },
  {
    providerName: "総務省統計局",
    name: "jSTAT MAP (地図で見る統計)",
    description: "国勢調査等の統計データを地図上で可視化・分析できるGISサービス。",
    officialUrl: "https://jstatmap.e-stat.go.jp/",
    category: "statistics",
    dataFormat: "HTML",
    accessType: "web",
    requiresApiKey: false,
    licenseName: "e-Stat 利用規約",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "yearly",
    trustLevel: 5,
    qualityScore: 75,
    tags: ["統計", "都市計画"],
    useCases: [{ useCaseName: "工事エリアの人口分布確認", description: "騒音影響世帯の概算" }],
  },
  {
    providerName: "総務省統計局",
    name: "統計ダッシュボード API",
    description: "主要な統計データをグラフ表示できる統計ダッシュボードのAPI。APIキー不要で利用可能。",
    officialUrl: "https://dashboard.e-stat.go.jp/",
    endpointUrl: "https://dashboard.e-stat.go.jp/api/1.0/Json/getData?IndicatorCode=0201010000000010000",
    documentationUrl: "https://dashboard.e-stat.go.jp/static/api",
    category: "statistics",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: false,
    licenseName: "e-Stat 利用規約",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "monthly",
    trustLevel: 5,
    qualityScore: 80,
    tags: ["統計"],
    useCases: [{ useCaseName: "主要指標の時系列取得", description: "建設投資等の推移把握" }],
  },
  {
    providerName: "東京都",
    name: "東京都オープンデータカタログサイト",
    description: "東京都と都内区市町村のオープンデータを横断検索できるカタログ。CKAN APIを提供。",
    officialUrl: "https://portal.data.metro.tokyo.lg.jp/",
    endpointUrl: "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?q=道路",
    category: "municipality",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: false,
    licenseName: "CC BY 4.0 (原則)",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "daily",
    trustLevel: 4,
    qualityScore: 80,
    tags: ["自治体", "統計"],
    useCases: [{ useCaseName: "都内の公共施設・避難所データ取得", targetSystem: "Disaster Insight Map" }],
  },
  {
    providerName: "静岡県",
    name: "VIRTUAL SHIZUOKA 点群データ",
    description: "静岡県が公開する3次元点群データ。G空間情報センターからダウンロード可能。",
    officialUrl: "https://www.geospatial.jp/ckan/dataset/shizuoka-2019-pointcloud",
    category: "3d-city",
    dataFormat: "other",
    accessType: "download",
    requiresApiKey: false,
    licenseName: "CC BY 4.0",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 4,
    qualityScore: 75,
    tags: ["3D都市", "地形", "自治体"],
    useCases: [{ useCaseName: "起工測量の事前検討", description: "点群による現況地形の把握" }],
  },
  {
    providerName: "北海道",
    name: "北海道オープンデータポータル",
    description: "北海道のオープンデータポータルサイト。防災・インフラ・統計等のデータを公開。",
    officialUrl: "https://www.harp.lg.jp/opendata/",
    category: "municipality",
    dataFormat: "CSV",
    accessType: "web",
    requiresApiKey: false,
    licenseName: "CC BY 4.0 (原則)",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 4,
    qualityScore: 65,
    tags: ["自治体", "統計"],
    useCases: [{ useCaseName: "道内の公共データ取得", description: "地域インフラ情報の参照" }],
  },
  {
    providerName: "BODIK(オープンデータ推進)",
    name: "BODIK オープンデータカタログ",
    description: "全国の自治体オープンデータを横断提供するカタログサイト。CKAN APIを利用可能。",
    officialUrl: "https://data.bodik.jp/",
    endpointUrl: "https://data.bodik.jp/api/3/action/package_search?q=避難所",
    category: "municipality",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: false,
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "daily",
    trustLevel: 3,
    qualityScore: 65,
    note: "データセットごとにライセンスが異なるため個別確認が必要",
    tags: ["自治体", "利用条件要確認"],
    useCases: [{ useCaseName: "自治体横断の避難所データ取得", targetSystem: "Disaster Insight Map" }],
  },
  {
    providerName: "デジタル庁",
    name: "調達ポータル (入札情報)",
    description: "国の機関の調達情報(入札公告・落札結果等)を横断検索できるポータル。",
    officialUrl: "https://www.p-portal.go.jp/",
    category: "construction",
    dataFormat: "HTML",
    accessType: "web",
    requiresApiKey: false,
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "daily",
    trustLevel: 5,
    qualityScore: 65,
    tags: ["利用条件要確認"],
    useCases: [{ useCaseName: "公共工事の案件調査", description: "入札公告のモニタリング" }],
  },
  {
    providerName: "デジタル庁",
    name: "e-Govデータポータル",
    description: "政府のオープンデータを横断的に検索できるデータカタログサイト。CKAN API対応。",
    officialUrl: "https://data.e-gov.go.jp/",
    endpointUrl: "https://data.e-gov.go.jp/data/api/3/action/package_search?q=道路",
    category: "statistics",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: false,
    licenseName: "政府標準利用規約",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "daily",
    trustLevel: 5,
    qualityScore: 75,
    tags: ["統計", "自治体"],
    useCases: [{ useCaseName: "政府データの横断検索", description: "一次データの所在確認" }],
  },
  {
    providerName: "科学技術振興機構(JST)",
    name: "J-STAGE",
    description: "国内の学協会誌等の学術論文プラットフォーム。土木学会論文集等を検索・閲覧可能。",
    officialUrl: "https://www.jstage.jst.go.jp/",
    endpointUrl: "https://api.jstage.jst.go.jp/searchapi/do?service=3&material=土木学会論文集",
    category: "research",
    dataFormat: "XML",
    accessType: "API",
    requiresApiKey: false,
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "daily",
    trustLevel: 5,
    qualityScore: 70,
    tags: ["利用条件要確認"],
    useCases: [{ useCaseName: "工法・技術の文献調査", description: "設計根拠の技術調査" }],
  },
  {
    providerName: "国立情報学研究所(NII)",
    name: "CiNii Research",
    description: "論文・研究データ・博士論文等を横断検索できる学術情報データベース。OpenSearch APIを提供。",
    officialUrl: "https://cir.nii.ac.jp/",
    endpointUrl: "https://cir.nii.ac.jp/opensearch/articles?q=地盤改良&format=json",
    documentationUrl: "https://support.nii.ac.jp/ja/cir/r_opensearch",
    category: "research",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: false,
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "daily",
    trustLevel: 5,
    qualityScore: 70,
    tags: ["利用条件要確認"],
    useCases: [{ useCaseName: "技術動向調査", description: "類似工事の研究事例確認" }],
  },
  {
    providerName: "国立情報学研究所(NII)",
    name: "KAKEN 科学研究費助成事業データベース",
    description: "科研費の採択課題・研究成果を検索できるデータベース。",
    officialUrl: "https://kaken.nii.ac.jp/",
    category: "research",
    dataFormat: "HTML",
    accessType: "web",
    requiresApiKey: false,
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 5,
    qualityScore: 60,
    tags: ["利用条件要確認"],
    useCases: [{ useCaseName: "先端研究の動向把握", description: "産学連携候補の調査" }],
  },
  {
    providerName: "工業所有権情報・研修館(INPIT)",
    name: "J-PlatPat (特許情報プラットフォーム)",
    description: "特許・実用新案・意匠・商標の公報等を検索できる特許情報プラットフォーム。",
    officialUrl: "https://www.j-platpat.inpit.go.jp/",
    category: "research",
    dataFormat: "HTML",
    accessType: "web",
    requiresApiKey: false,
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "weekly",
    trustLevel: 5,
    qualityScore: 65,
    tags: ["利用条件要確認"],
    useCases: [{ useCaseName: "工法特許の調査", description: "新工法採用時の権利確認" }],
  },
  {
    providerName: "産業技術総合研究所",
    name: "20万分の1日本シームレス地質図 API",
    description: "全国の地質図をシームレスに提供。凡例・地質情報をAPIで取得可能。",
    officialUrl: "https://gbank.gsj.jp/seamless/",
    endpointUrl: "https://gbank.gsj.jp/seamless/v2/api/1.3.1/legend.json",
    documentationUrl: "https://gbank.gsj.jp/seamless/v2/api/1.3.1/",
    category: "gis",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: false,
    licenseName: "CC BY 4.0",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 5,
    qualityScore: 85,
    tags: ["地形", "工事候補地"],
    useCases: [{ useCaseName: "工事候補地の地質確認", targetSystem: "Site Risk Checker" }],
  },
  {
    providerName: "産業技術総合研究所",
    name: "地質図Navi",
    description: "各種地質図・活断層情報等を地図上で閲覧できるサービス。",
    officialUrl: "https://gbank.gsj.jp/geonavi/",
    category: "gis",
    dataFormat: "HTML",
    accessType: "web",
    requiresApiKey: false,
    licenseName: "CC BY 4.0 (データによる)",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 5,
    qualityScore: 75,
    tags: ["地形", "災害"],
    useCases: [{ useCaseName: "活断層位置の確認", targetSystem: "Site Risk Checker" }],
  },
  {
    providerName: "JAXA",
    name: "ALOS 全球数値地表モデル (AW3D30)",
    description: "全球の30mメッシュ数値地表モデル(DSM)。広域地形解析に利用可能(要利用者登録)。",
    officialUrl: "https://www.eorc.jaxa.jp/ALOS/jp/dataset/aw3d30/aw3d30_j.htm",
    category: "map-elevation",
    dataFormat: "other",
    accessType: "download",
    requiresApiKey: false,
    commercialUse: "restricted",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 5,
    qualityScore: 70,
    note: "利用には登録が必要。商用利用条件は要確認",
    tags: ["標高", "地形", "利用条件要確認"],
    useCases: [{ useCaseName: "海外案件の広域地形把握", description: "全球DSMの活用" }],
  },
  {
    providerName: "USGS",
    name: "USGS Earthquake API",
    nameEn: "USGS Earthquake Hazards API",
    description: "米国地質調査所の地震カタログAPI。世界の地震情報をGeoJSONで取得可能。",
    officialUrl: "https://earthquake.usgs.gov/",
    endpointUrl: "https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&limit=1",
    documentationUrl: "https://earthquake.usgs.gov/fdsnws/event/1/",
    category: "weather",
    dataFormat: "GeoJSON",
    accessType: "API",
    requiresApiKey: false,
    licenseName: "Public Domain (USGS)",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "realtime",
    trustLevel: 5,
    qualityScore: 85,
    tags: ["災害"],
    useCases: [{ useCaseName: "世界の地震情報モニタリング", description: "海外拠点のリスク把握" }],
  },
  {
    providerName: "OpenStreetMap Foundation",
    name: "Nominatim (ジオコーディング)",
    nameEn: "Nominatim",
    description: "OSMデータによる住所⇔座標変換(ジオコーディング)サービス。利用ポリシーの遵守が必要。",
    officialUrl: "https://nominatim.org/",
    endpointUrl: "https://nominatim.openstreetmap.org/status",
    documentationUrl: "https://nominatim.org/release-docs/latest/api/Overview/",
    category: "map",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: false,
    licenseName: "ODbL 1.0 / Nominatim Usage Policy",
    commercialUse: "restricted",
    attributionRequired: true,
    updateFrequency: "realtime",
    trustLevel: 4,
    qualityScore: 70,
    note: "公開サーバは1リクエスト/秒等の利用ポリシーあり。大量利用は自前ホスティング推奨",
    tags: ["利用条件要確認"],
    useCases: [{ useCaseName: "現場住所の座標変換", description: "地図表示・距離計算の前処理" }],
  },
  {
    providerName: "国土交通省",
    name: "G空間情報センター",
    description: "産官学の地理空間情報を流通させるプラットフォーム。点群・都市モデル等の多様なデータを提供。",
    officialUrl: "https://front.geospatial.jp/",
    endpointUrl: "https://www.geospatial.jp/ckan/api/3/action/package_search?q=点群",
    category: "gis",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: false,
    commercialUse: "unknown",
    attributionRequired: true,
    updateFrequency: "daily",
    trustLevel: 4,
    qualityScore: 75,
    note: "データセットごとにライセンスが異なるため個別確認が必要",
    tags: ["地形", "3D都市", "利用条件要確認"],
    useCases: [{ useCaseName: "地理空間データの横断検索", description: "点群・GISデータの入手" }],
  },
  {
    providerName: "国土交通省",
    name: "位置参照情報ダウンロードサービス",
    description: "大字・町丁目レベルの位置参照情報(住所と座標の対応)を提供するサービス。",
    officialUrl: "https://nlftp.mlit.go.jp/isj/",
    category: "gis",
    dataFormat: "CSV",
    accessType: "download",
    requiresApiKey: false,
    licenseName: "国土交通省 位置参照情報 利用約款",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "yearly",
    trustLevel: 5,
    qualityScore: 80,
    tags: ["統計", "地形"],
    useCases: [{ useCaseName: "住所データの座標化", description: "台帳住所の地図プロット" }],
  },
  {
    providerName: "国土交通省",
    name: "PLATEAU VIEW",
    description: "PLATEAU 3D都市モデルをブラウザで閲覧できるビューア。データセットの確認に利用。",
    officialUrl: "https://plateauview.mlit.go.jp/",
    category: "3d-city",
    dataFormat: "HTML",
    accessType: "web",
    requiresApiKey: false,
    licenseName: "PLATEAU Sites 利用規約",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "yearly",
    trustLevel: 5,
    qualityScore: 75,
    tags: ["3D都市", "都市計画"],
    useCases: [{ useCaseName: "都市モデルの事前確認", description: "対象地区のデータ整備状況確認" }],
  },
  {
    providerName: "気象庁",
    name: "高解像度降水ナウキャスト",
    description: "250mメッシュの降水短時間予報を地図表示するサービス。",
    officialUrl: "https://www.jma.go.jp/bosai/nowc/",
    category: "weather",
    dataFormat: "HTML",
    accessType: "web",
    requiresApiKey: false,
    licenseName: "気象庁ホームページ利用規約",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "realtime",
    trustLevel: 5,
    qualityScore: 75,
    tags: ["気象", "施工判断"],
    useCases: [{ useCaseName: "コンクリート打設時の降雨監視", targetSystem: "Weather & Water Decision" }],
  },
  {
    providerName: "国土交通省",
    name: "重要水防箇所",
    description: "河川の重要水防箇所(洪水時に危険が予想される箇所)の情報。国土数値情報等で提供。",
    officialUrl: "https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-A22.html",
    category: "gis",
    dataFormat: "GeoJSON",
    accessType: "download",
    requiresApiKey: false,
    licenseName: "国土数値情報ダウンロードサービス利用約款",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "irregular",
    trustLevel: 5,
    qualityScore: 75,
    tags: ["河川", "災害", "工事候補地"],
    useCases: [{ useCaseName: "河川工事の水防リスク確認", targetSystem: "Site Risk Checker" }],
  },
  // ===== 2026-08-10 追加 (実データ50種コネクタ拡充: 公式JSON API 5種) =====
  {
    providerName: "気象庁",
    name: "気象庁 地震情報JSON",
    nameEn: "JMA Earthquake Information JSON",
    description:
      "気象庁が提供する地震情報(震源・震度)のJSON一覧。全国の地震発生情報をリアルタイムで機械判読可能。",
    officialUrl: "https://www.jma.go.jp/bosai/quake/data/list.json",
    endpointUrl: "https://www.jma.go.jp/bosai/quake/data/list.json",
    documentationUrl: "https://www.jma.go.jp/jma/kishou/info/coment.html",
    category: "weather",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: false,
    licenseName: "気象庁ホームページ利用規約 (CC BY 4.0 互換)",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "realtime",
    trustLevel: 5,
    qualityScore: 88,
    tags: ["災害", "気象", "施工判断"],
    useCases: [{ useCaseName: "工事現場周辺の地震発生モニタリング", targetSystem: "Site Risk Checker" }],
  },
  {
    providerName: "気象庁",
    name: "気象庁 津波情報JSON",
    nameEn: "JMA Tsunami Information JSON",
    description:
      "気象庁が提供する津波予報・注意報・警報のJSON一覧。沿岸工事・海上作業のリスク判断に利用できる。",
    officialUrl: "https://www.jma.go.jp/bosai/tsunami/data/list.json",
    endpointUrl: "https://www.jma.go.jp/bosai/tsunami/data/list.json",
    documentationUrl: "https://www.jma.go.jp/jma/kishou/know/tsunami/tsunami-note.html",
    category: "weather",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: false,
    licenseName: "気象庁ホームページ利用規約 (CC BY 4.0 互換)",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "realtime",
    trustLevel: 5,
    qualityScore: 88,
    tags: ["災害", "気象", "施工判断"],
    useCases: [{ useCaseName: "海上工事の津波リスク確認", targetSystem: "Weather & Water Decision" }],
  },
  {
    providerName: "国土地理院",
    name: "国土地理院 住所検索API",
    nameEn: "GSI Address Search API",
    description:
      "国土地理院の電子国土基本図に基づく住所→座標変換API(ジオコーディング)。現場住所の緯度経度特定に利用できる。",
    officialUrl: "https://msearch.gsi.go.jp/",
    endpointUrl: "https://msearch.gsi.go.jp/address-search/AddressSearch?q=東京都千代田区",
    documentationUrl: "https://msearch.gsi.go.jp/",
    category: "gis",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: false,
    licenseName: "国土地理院コンテンツ利用規約",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "realtime",
    trustLevel: 5,
    qualityScore: 88,
    tags: ["地形", "工事候補地"],
    useCases: [{ useCaseName: "現場住所の座標特定", targetSystem: "Site Risk Checker" }],
  },
  {
    name: "Open-Meteo 大気質API (参考)",
    providerName: "Open-Meteo",
    nameEn: "Open-Meteo Air Quality API (reference)",
    description:
      "Open-Meteoが提供する大気質(PM2.5・PM10等)の参考API。出典はCopernicus等の公開データ。公式一次情報ではないため参考情報として扱う。",
    officialUrl: "https://open-meteo.com/en/docs/air-quality-api",
    endpointUrl:
      "https://air-quality-api.open-meteo.com/v1/air-quality?latitude=35.68&longitude=139.76&hourly=pm10,pm2_5&timezone=Asia/Tokyo",
    documentationUrl: "https://open-meteo.com/en/docs/air-quality-api",
    category: "weather",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: false,
    licenseName: "CC BY 4.0 (参照元データ)", 
    commercialUse: "restricted",
    attributionRequired: true,
    updateFrequency: "hourly",
    trustLevel: 3,
    qualityScore: 70,
    note: "参考情報。施工判断の入力には使用しない。",
    tags: ["気象", "施工判断"],
    useCases: [{ useCaseName: "現場周辺の大気質参考確認", targetSystem: "Weather & Water Decision" }],
  },
  {
    name: "Open-Meteo 週間予報API (参考)",
    providerName: "Open-Meteo",
    nameEn: "Open-Meteo Forecast API (reference)",
    description:
      "Open-Meteoが提供する週間予報の参考API。気象庁の公式情報ではないため、注意報・警報は必ず気象庁を確認する。",
    officialUrl: "https://open-meteo.com/",
    endpointUrl:
      "https://api.open-meteo.com/v1/forecast?latitude=35.68&longitude=139.76&daily=weather_code,temperature_2m_max&timezone=Asia/Tokyo",
    documentationUrl: "https://open-meteo.com/en/docs",
    category: "weather",
    dataFormat: "JSON",
    accessType: "API",
    requiresApiKey: false,
    licenseName: "CC BY 4.0",
    commercialUse: "restricted",
    attributionRequired: true,
    updateFrequency: "hourly",
    trustLevel: 3,
    qualityScore: 70,
    note: "参考情報。週間予報表示に利用。気象庁の注意報・警報は別途確認必須。",
    tags: ["気象", "施工判断"],
    useCases: [{ useCaseName: "現場の週間予報参考確認", targetSystem: "Weather & Water Decision" }],
  },
  // ===== 2026-08-12 追加 (一次情報・HTTP 200実測確認済み 5件) =====
  {
    providerName: "国土地理院",
    name: "地理院地図",
    nameEn: "GSI Maps",
    description:
      "国土地理院の地理院地図。地形図・空中写真・標高・傾斜量図などのタイルを現場調査や報告書作成に利用できる。",
    officialUrl: "https://maps.gsi.go.jp/",
    documentationUrl: "https://maps.gsi.go.jp/development/ichiran.html",
    category: "map",
    dataFormat: "PNG",
    accessType: "tile",
    requiresApiKey: false,
    licenseName: "国土地理院コンテンツ利用規約",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "monthly",
    trustLevel: 5,
    qualityScore: 85,
    note: "2026-08-12 HTTP 200実測確認。地形分析画面の背景地図に利用。",
    tags: ["地形", "地図", "工事候補地"],
    useCases: [{ useCaseName: "現場周辺の地形・標高確認", targetSystem: "Terrain Risk Viewer" }],
  },
  {
    providerName: "気象庁",
    name: "気象庁 波浪予想図",
    nameEn: "JMA Wave Forecast Chart",
    description:
      "気象庁が提供する日本近海の波浪予想図。海上工事・潜水作業の海象確認に利用できる一次情報。",
    officialUrl: "https://www.jma.go.jp/jp/wave/",
    documentationUrl: "https://www.jma.go.jp/jma/kishou/know/yougo_hp/wave.html",
    category: "weather",
    dataFormat: "PNG",
    accessType: "web",
    requiresApiKey: false,
    licenseName: "気象庁ホームページ利用規約",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "daily",
    trustLevel: 5,
    qualityScore: 85,
    note: "2026-08-12 HTTP 200実測確認。数値データはOpen-Meteo Marine(参考)と併用。",
    tags: ["気象", "海象", "施工判断"],
    useCases: [{ useCaseName: "海上工事の波浪リスク確認", targetSystem: "Weather & Water Decision" }],
  },
  {
    providerName: "JAXA",
    name: "JAXA GSMaP 全球降水マップ",
    nameEn: "JAXA GSMaP Global Precipitation",
    description:
      "JAXAが提供する衛星ベースの全球降水マップ。雨量観測の乏しい地域での参考情報として利用できる。",
    officialUrl: "https://sharaku.eorc.jaxa.jp/GSMaP/",
    documentationUrl: "https://sharaku.eorc.jaxa.jp/GSMaP/",
    category: "weather",
    dataFormat: "PNG",
    accessType: "web",
    requiresApiKey: false,
    licenseName: "JAXA利用条件",
    commercialUse: "restricted",
    attributionRequired: true,
    updateFrequency: "hourly",
    trustLevel: 4,
    qualityScore: 75,
    note: "2026-08-12 HTTP 200実測確認。予報ではなく実況の参考情報として扱う。",
    tags: ["気象", "災害"],
    useCases: [{ useCaseName: "広域の降水状況参考確認", targetSystem: "Weather & Water Decision" }],
  },
  {
    providerName: "国土交通省",
    name: "道路の有料道路情報",
    nameEn: "MLIT Toll Road Information",
    description:
      "国土交通省が提供する有料道路の路線・料金情報。工事に伴う通行規制・物流ルート検討の参考にできる。",
    officialUrl: "https://www.mlit.go.jp/road/yuryo/",
    documentationUrl: "https://www.mlit.go.jp/road/yuryo/",
    category: "road",
    dataFormat: "HTML",
    accessType: "web",
    requiresApiKey: false,
    licenseName: "国交省サイト利用条件",
    commercialUse: "allowed",
    attributionRequired: true,
    updateFrequency: "yearly",
    trustLevel: 4,
    qualityScore: 70,
    note: "2026-08-12 HTTP 200実測確認。",
    tags: ["道路", "交通"],
    useCases: [{ useCaseName: "物流ルート・通行料金の参考確認", targetSystem: "Site Risk Checker" }],
  },
  {
    providerName: "国土交通省",
    name: "国土技術政策総合研究所 研究成果",
    nameEn: "NILIM Research Outputs",
    description:
      "国土技術政策総合研究所(国総研)が公開する研究成果・技術資料。設計基準や維持管理の最新動向確認に利用できる。",
    officialUrl: "https://www.nilim.go.jp/",
    documentationUrl: "https://www.nilim.go.jp/lab/bcg/siryou/index.html",
    category: "research",
    dataFormat: "PDF",
    accessType: "web",
    requiresApiKey: false,
    licenseName: "国総研サイト利用条件",
    commercialUse: "restricted",
    attributionRequired: true,
    updateFrequency: "monthly",
    trustLevel: 4,
    qualityScore: 75,
    note: "2026-08-12 HTTP 200実測確認。",
    tags: ["研究", "維持管理"],
    useCases: [{ useCaseName: "設計基準・技術資料の調査", targetSystem: "Civil Engineering Research" }],
  },
];
